image: openjdk:11

stages:
  - build
  - test
  - release
  - deploy

before_script:
  - chmod +x gradlew
  - export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

build:
  stage: build
  script: ./gradlew build
  artifacts:
    paths:
      - build/libs/tools-*.jar
  only:
    - branches

test:
  stage: test
  script: ./gradlew check
  only:
    - branches

release:
  stage: release
  script: ./gradlew release -Prelease.disableChecks
  only:
    - master

publish:
  stage: deploy
  script: ./gradlew publish
  only:
    - master

buildImage:
  stage: deploy
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
  only:
    - tags

after_script:
  - echo - "End of CI script"


#
#publishImage:
#  stage: deploy
#  script:
#  only:
#    - master


