image: openjdk:11

workflow:
  rules:
    - if: $CI_COMMIT_REF_NAME =~ /-wip$/
      when: never

stages:
  - build
  - test
  - release
  - deploy

before_script:
  - chmod +x gradlew

build:
  stage: build
  script: ./gradlew build
  artifacts:
    paths:
      - build/libs/tools-*.jar
  only:
    - branches

test:
  stage: test
  script: ./gradlew check
  only:
    - branches

release:
  stage: release
  script: ./gradlew release
  only:
    - master

publish:
  stage: deploy
  script: ./gradlew publish
  only:
    - master


#buildImage:
#  stage: deploy
#  script:
#  only:
#    - master
#
#publishImage:
#  stage: deploy
#  script:
#  only:
#    - master


