image: openjdk:11

stages:
  - build
  - deploy

before_script:
  - chmod +x gradlew

build:
  stage: build
  script: ./gradlew build
  artifacts:
    paths:
      - build/libs/tools-*-SNAPSHOT.jar

publish:
  stage: deploy
  script: ./gradlew publish
