version: 2.1

commands:
  setup:
    description: Setup Gradle Environment
    steps:
      - run: chmod +x gradlew
      - run: export GRADLEW_USER_HOME=`pwd`:/.gradle

  restore-cache:
    steps:
      - restore_cache:
          keys:
            - gradle-cache-v1-{{ .Branch }}-{{ checksum "build.gradle" }}
            - gradle-cache-v1-{{ .Branch }}
            - gradle-cache-v1

  save-cache:
    steps:
      - save_cache:
          key: gradle-cache-v1-{{ .Branch }}-{{ checksum "build.gradle" }}
          paths:
            - ~/.gradle
  gbuild:
    description: Gradle Build
    steps:
      - run: git status  && ./gradlew build -Preckon.stage=final

  test:
    description: Gradle Unit test
    steps:
      - run: ./gradlew check

  release:
    description: Publish to Artifact Repository
    steps:
      - run:
          name: "Configure git"
          command: |
            git config user.email "aengus.mccullough@gmail.com"
            git config user.name "CI Robot"

      - run:
          name: "Push release tag"
          command: |
                    if [ "${CIRCLE_BRANCH}" == "master" ];
                      then
                      ./gradlew  build  reckonTagPush -Preckon.scope=minor -Preckon.stage=final -PgitlabAccessToken=${GITLAB_ACCESS_TOKEN}
                    elif [ "${CIRCLE_BRANCH}" == "develop" ];
                      then
                      ./gradlew  build  reckonTagPush -Preckon.scope=minor -Preckon.stage=rc -PgitlabAccessToken=${GITLAB_ACCESS_TOKEN}
                    fi
      - run:
          name: "Publish binary"
          command: ./gradlew publish -PgitlabAccessToken=${GITLAB_ACCESS_TOKEN}

      - run:
          name: "Install std-changelog"
          command: |
                     sudo npm install -g npm
                     npm install --save-dev standard-changelog
      - run:
          name: "Generate Changelog"
          command:  npx standard-changelog
      - run:
          name: " Commit & Push Changelog"
          command: |
              git checkout ${CIRCLE_BRANCH}
              git add CHANGELOG.md
              git commit -m "docs(CHANGELOG.md) update changelog with latest release notes [skip ci]"
              git push origin ${CIRCLE_BRANCH}


  extract_version:
    description: Parse Version Name from library
    steps:
      - run: |
              jar=`ls /home/circleci/repo/build/libs`
               echo $jar
               echo ${jar:6}
                echo `basename  ${jar:6} .jar `
               echo `basename  ${jar:6} .jar ` > /home/circleci/repo/build/libs/version.txt
                cat /home/circleci/repo/build/libs/version.txt

  install_deps:
    description: Install Docker Image Deps
    steps:
      - run: |
          apk add --no-cache \
          py-pip=9.0.0-r1
          pip install \
          docker-compose==1.12.0 \
          awscli==1.11.76

jobs:

  buildJar:
    docker:
      - image: circleci/openjdk:11-jdk-buster-node
    working_directory: /home/circleci/repo
    steps:
      - checkout
      - setup
      - add_ssh_keys:
          fingerprints:
            - "52:95:61:f3:cd:7a:d0:6a:10:fe:58:36:21:ef:c5:40"
      - restore-cache
      - gbuild
      - persist_to_workspace:
          root: build
          paths:
            - libs
      - test
      - run: ./gradlew sendCoverageToCodacy
      - store_test_results:
          path: build/test-results/test
      - store_artifacts:
          path: build/test-results/test
          when: always
      - save-cache

  release:
    docker:
      - image: circleci/openjdk:11-jdk-buster-node
    environment:
      GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2"
    working_directory: /home/circleci/repo
    steps:
      - checkout
      - setup
      - add_ssh_keys:
          fingerprints:
            - "52:95:61:f3:cd:7a:d0:6a:10:fe:58:36:21:ef:c5:40"
      - restore-cache
      - run: mkdir build
      - attach_workspace:
          at: /home/circleci/repo/build
      - release
      - store_artifacts:
          path: build/libs/version.txt
          when: always
  buildDockerImage:
    docker:
      - image: docker:17.05.0-ce-git
    working_directory: /home/circleci/repo
    steps:
      - checkout
      - setup_remote_docker
      - install_deps
      - restore_cache:
          keys:
            - v1-{{ .Branch }}
          paths:
            - /caches/app.tar
      - run: mkdir build
      - attach_workspace:
          at: /home/circleci/repo/build
      - extract_version
      - run:
          name: "Check version exists"
          command: |
                     ls -l /home/circleci/repo/build/libs
                     cat /home/circleci/repo/build/libs/version.txt
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /caches/app.tar | true
      - run:
          name: Build application Docker image
          command: |
            docker build --cache-from=app -t app .
      - run:
          name: Save Docker image layer cache
          command: |
            mkdir -p /caches
            docker save -o /caches/app.tar app
      - save_cache:
          key: v1-{{ .Branch }}-{{ epoch }}
          paths:
            - /caches/app.tar
      - store_artifacts:
          path: /caches/app.tar
          destination: docker-image
      - run:
          name: Publish to Docker registry
          command: |
            TAG=`cat /home/circleci/repo/build/libs/version.txt`
            echo $TAG
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker image tag app:latest ${DOCKER_USER}/crunch-ski-tools:${TAG}
            docker image push ${DOCKER_USER}/crunch-ski-tools:${TAG}


workflows:
  version: 2.1
  standard_workflow:
    jobs:
      - buildJar:
          context: tools-context
      - release:
          context: tools-context
          requires:
            - buildJar
          filters:
            branches:
              only:
                - master
                - develop
      - buildDockerImage:
          context: tools-context
          requires:
            - release
          filters:
            branches:
              only:
                - master
                - develop