version: 2.1

commands:
  setup:
    steps:
      - run: chmod +x gradlew
      - run: export GRADLEW_USER_HOME=`pwd`:/.gradle
      - restore_cache:
          keys:
            - gradle-cache-v1-{{ .Branch }}-{{ checksum "build.gradle" }}
            - gradle-cache-v1-{{ .Branch }}
            - gradle-cache-v1
  save-cache:
    steps:
      - save_cache:
          key: gradle-cache-v1-{{ .Branch }}-{{ checksum "build.gradle" }}
          paths:
            - ~/.gradle
  build:
    steps: ./gradlew build

  test:
    steps: ./gradlew test

  release:
    steps: ./gradlew release

jobs:
  build:
    docker:
      - image: circleci/openjdk:openjdk-11-boot-stretch-node
    working_directory: /home/circleci/repo

    steps:
      - checkout
      - restore-cache
      - build
      - test
      - release

workflows:
  version: 2.1
  standard_workflow:
    jobs:
      - build:
          context: sls-context