version: 2.1
orbs:
  openjdk-install: entur/vm-install-tools@0.0.6

commands:
  setup:
    steps:
      - openjdk-install/install-java-11
      - run: chmod +x gradlew
      - run: export GRADLEW_USER_HOME=`pwd`:/.gradle

  restore-cache:
    steps:
      - restore_cache:
          keys:
            - gradle-cache-v1-{{ .Branch }}-{{ checksum "build.gradle" }}
            - gradle-cache-v1-{{ .Branch }}
            - gradle-cache-v1

  save-cache:
    steps:
      - save_cache:
          key: gradle-cache-v1-{{ .Branch }}-{{ checksum "build.gradle" }}
          paths:
            - ~/.gradle
  gbuild:
    steps:
      - run: ./gradlew build -Preckon.scope=minor -Preckon.stage=rc

  test:
    steps:
      - run: ./gradlew check

  release:
    steps:
      - run: git config user.email "aengus.mccullough@gmail.com"
      - run: git config user.name "CI Robot"
      - run: ./gradlew reckonTagPush -Preckon.scope=minor -Preckon.stage=rc

  installDeps:



jobs:

  buildDockerImage:
    docker:
      - image: docker:17.05.0-ce-git
    working_directory: /home/circleci/repo
    steps:
      - setup
      - add_ssh_keys:
          fingerprints:
            - "52:95:61:f3:cd:7a:d0:6a:10:fe:58:36:21:ef:c5:40"
      - checkout
      - restore-cache
      - gbuild
      - test
      #- release
      - save-cache
      - setup_remote_docker
      - run:
          name: Install Dependencies
          command: |
            apk add --no-cache \
            py-pip=9.0.0-r1
            pip install \
            docker-compose==1.12.0 \
            awscli==1.11.76
      - restore_cache:
          keys:
            - v1-{{ .Branch }}
          paths:
            - /caches/app.tar
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /caches/app.tar | true
      - run:
          name: Build application Docker image
          command: |
            docker build --cache-from=app -t app .
      - run:
          name: Save Docker image layer cache
          command: |
            mkdir -p /caches
            docker save -o /caches/app.tar app
      - save_cache:
          key: v1-{{ .Branch }}-{{ epoch }}
          paths:
            - /caches/app.tar
      - store_artifacts:
          path: /caches/app.tar
          destination: docker-image

workflows:
  version: 2.1
  standard_workflow:
    jobs:
      - buildDockerImage:
          context: tools-context